### ISSUE TITLE
Image not loading when cache-src expression changes using watch instead of observe

### ISSUE THREAD

**Issue by mklilley** [BenBBear/ionic-cache-src#16]
Hi,
When you did your update "support video/audio, bug fixes for several issues"  you changed observe to watch.  Since then when i have an expression like this
`cache-src={{::somevariable}} `
The image fails to load when the value of somevariable is set some time after the view has loaded.
I also tried it without angular one time binding (the ::) but i still couldn't get the image to load.
When i reverted back to observe, everything worked again. 

Thanks,

Matt

**Comment by BenBBear** [comment]
I change it to `scope` because someone reports `observe` doesn't work for some android webview. Now seems `observe` actually covers a broader audience. Will change it back. 

And the difference between `watcher` and `observer` is discussed here: http://stackoverflow.com/questions/14876112/angularjs-difference-between-the-observe-and-watch-methods . `Observe` is for DOM attribute, which makes more sense here.
